# creating a cluster peering is only required when using 2 separate clusters
- name: Create cluster peer
  netapp.ontap.na_ontap_cluster_peer:
    state: present
    source_intercluster_lifs: "{{ item.src_lif }}"
    dest_intercluster_lifs: "{{ item.dst_lif }}"
    passphrase: "{{ passphrase }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    dest_hostname: "{{ netapp_hostname }}"
    https: true
    validate_certs: false
  with_items: "{{ SnapMirror_Global_Config }}"
  when: item.local_cluster == false

# the peer_cluster parameter is only required when using 2 separate clusters
- name: Create vserver peer (in 2 separate clusters)
  netapp.ontap.na_ontap_vserver_peer:
    state: present
    peer_vserver: "{{ item.dst_vserver }}"
    peer_cluster: "{{ netapp_hostname }}"
    vserver: "{{ item.src_vserver }}"
    applications: snapmirror
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    dest_hostname: "{{ netapp_hostname }}"
    https: true
    validate_certs: false
  with_items: "{{ SnapMirror_Global_Config }}"
  when: item.local_cluster == false

- name: Create vserver peer  (in a local cluster)
  netapp.ontap.na_ontap_vserver_peer:
    state: present
    peer_vserver: "{{ item.dst_vserver }}"
    vserver: "{{ item.src_vserver }}"
    applications: snapmirror
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    dest_hostname: "{{ netapp_hostname }}"
    https: true
    validate_certs: false
  with_items: "{{ SnapMirror_Global_Config }}"
  when: item.local_cluster == true

- name: Create SnapMirror
  netapp.ontap.na_ontap_snapmirror:
    state: present
    source_endpoint:
          path: "{{ item.src_vserver + ':' + item.src_volume }}"
    destination_endpoint:
          path: "{{ item.dst_vserver + ':' + item.dst_volume }}"
    create_destination:
          enabled: true
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
  with_items: "{{ SnapMirror_Volumes_Config }}"