---
- name: Deploy ONTAP Cluster config
  hosts: localhost
  collections:
    - netapp.ontap
  roles:
    - role: /etc/ansible/LabAnsible/LabAnsibleDockerPlugin/1_Lab_NAS/3-svm-create

- name: Mount export to rhel
  hosts: rhel
  roles:  
    - role: /etc/ansible/LabAnsible/LabAnsibleDockerPlugin/1_Lab_NAS/3-mount-nfs